# Computational Linear Algebra: PCA Homework

## Exercise 0.0: Initialization
Fill the missing values in this text box. **Remove the information of the second student if you are not working in a team**.

**Academic Year:** 2025/2026

### Team Members (Alphabetical Order):
1. Ozkan, Omer (360761);
2. Ulas, Zeynep Sude (364189).

Now, fill the python list below with the Student IDs of the team

In [6]:
StudentIDs = [364189,360761]  # <-------- Fill this list with Student IDs of the team

# Our student IDS

## Exercise 0.1: Starting Code-Cell

Download the .csv files from the web page of the course (*responses_hw.csv* and *columns_hw.csv*) and past them in **the same folder of this notebook**.


Then, run the cell below, **without modifing any line of code**.

The output of this code cell is **your personal subset of the original dataset**, with 2/3 of the original features (i.e., columns) and 3/4 of the original persons (i.e., rows).

### ATTENTION: DO NOT CHANGE THE CODE INSIDE THE FOLLOWING CELL, ANY CHANGE CAN INVALIDATE THE HOMEWORK!

In [7]:
####################################################################
############## DO NOT CHANGE THE CODE IN THIS CELL #################
####################################################################

import numpy as np
import pandas as pd
from IPython.display import display

var_entertainment_feat_types = ['Interests', 'Movies', 'Music']
var_personal_feat_types = ['Finance', 'Phobias']
fixed_feat_types = ['Personality', 'Health']

label_types = ['Demographic']

variables_by_type = {
    'Demographics': ['Age', 'Height', 'Weight', 'Number of siblings', 
                     'Gender', 'Hand', 'Education', 'Only child', 'Home Town Type',
                     'Home Type'],
    'Finance': ['Finances', 'Shopping centres', 'Branded clothing', 
                'Entertainment spending', 'Spending on looks', 
                'Spending on gadgets', 'Spending on healthy eating'],
    'Health': ['Smoking', 'Alcohol', 'Healthy eating'],
    'Interests': ['History', 'Psychology', 'Politics', 'Mathematics', 
                  'Physics', 'Internet', 'PC', 'Economy Management', 
                  'Biology', 'Chemistry', 'Reading', 'Geography', 
                  'Foreign languages', 'Medicine', 'Law', 'Cars', 
                  'Art exhibitions', 'Religion', 'Countryside, outdoors', 
                  'Dancing', 'Musical instruments', 'Writing', 'Passive sport', 
                  'Active sport', 'Gardening', 'Celebrities', 'Shopping', 
                  'Science and technology', 'Theatre', 'Fun with friends', 
                  'Adrenaline sports', 'Pets'],
    'Movies': ['Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 
               'Sci-fi', 'War', 'Fantasy/Fairy tales', 'Animated', 
               'Documentary', 'Western', 'Action'],
    'Music': ['Music', 'Slow songs or fast songs', 'Dance', 'Folk', 
              'Country', 'Classical music', 'Musical', 'Pop', 'Rock', 
              'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 
              'Swing, Jazz', 'Rock n roll', 'Alternative', 'Latino', 
              'Techno, Trance', 'Opera'],
    'Personality': ['Daily events', 'Prioritising workload', 
                    'Writing notes', 'Workaholism', 'Thinking ahead', 
                    'Final judgement', 'Reliability', 'Keeping promises', 
                    'Loss of interest', 'Friends versus money', 'Funniness', 
                    'Fake', 'Criminal damage', 'Decision making', 'Elections', 
                    'Self-criticism', 'Judgment calls', 'Hypochondria', 
                    'Empathy', 'Eating to survive', 'Giving', 
                    'Compassion to animals', 'Borrowed stuff', 
                    'Loneliness', 'Cheating in school', 'Health', 
                    'Changing the past', 'God', 'Dreams', 'Charity', 
                    'Number of friends', 'Punctuality', 'Lying', 'Waiting', 
                    'New environment', 'Mood swings', 'Appearence and gestures', 
                    'Socializing', 'Achievements', 'Responding to a serious letter', 
                    'Children', 'Assertiveness', 'Getting angry', 
                    'Knowing the right people', 'Public speaking', 
                    'Unpopularity', 'Life struggles', 'Happiness in life', 
                    'Energy levels', 'Small - big dogs', 'Personality', 
                    'Finding lost valuables', 'Getting up', 'Interests or hobbies', 
                    "Parents' advice", 'Questionnaires or polls', 'Internet usage'],
    'Phobias': ['Flying', 'Storm', 'Darkness', 'Heights', 'Spiders', 'Snakes', 
                'Rats', 'Ageing', 'Dangerous dogs', 'Fear of public speaking']
}

labels = variables_by_type['Demographics']
features_all = []
for tt in variables_by_type.keys():
    if tt != 'Demographics':
        features_all += variables_by_type[tt]

def which_features(*StudentIDs):
    random_seed = min(StudentIDs)
    np.random.seed(random_seed)
    features_ = np.random.choice(features_all, int((2 * len(features_all)) / 3), replace=False).tolist()
    features = []
    features_by_type = {tt: [] for tt in variables_by_type.keys() if tt != 'Demographics'}
    for tt in variables_by_type.keys():
        ft_list = variables_by_type[tt]
        for ii in range(len(ft_list)):
            if ft_list[ii] in features_:
                features.append(ft_list[ii])
                features_by_type[tt].append(ft_list[ii])

    return features, features_by_type

features, features_by_type = which_features(*StudentIDs)

print(f'*** THESE ARE THE {len(features)} SELECTED FEATURES (SEE VARIABLE features):')
for ff in features:
    print(f'{ff}')
print('*************************************')
print('')
print('*** SELECTED FEATURES BY TYPES (SEE VARIABLE features_by_type):')
for tt in features_by_type.keys():
    print(f'{tt}: {features_by_type[tt]}')
    print('')
print('*************************************')
print('')
print('*** THESE ARE THE LABELS (SEE VARIABLE labels):')
for ll in labels:
    print(f'{ll}')
print('*************************************')

def which_rows(df, frac, *StudentIDs):
    random_seed = min(StudentIDs)
    df_ = df.sample(frac=frac, random_state=random_seed)
    return df_

responses_hw = pd.read_csv('responses_hw.csv', index_col=0)
responses = which_rows(responses_hw, 0.75, *StudentIDs)
responses = responses.loc[:, features + labels]

responses_ft = responses.loc[:, features]
responses_lb = responses.loc[:, labels]

print('')
print('*** THIS IS YOUR PERSONAL DATASET (features AND labels TOGETHER, SEE VARIABLE responses)')
display(responses)
print('')
print('*** THIS IS YOUR PERSONAL DATASET (features, SEE VARIABLE responses_ft)')
display(responses_ft)
print('')
print('*** THIS IS YOUR PERSONAL DATASET (labels, SEE VARIABLE responses_lb)')
display(responses_lb)

random_seed = min(StudentIDs)
np.random.seed(random_seed)

your_scaler = np.random.choice(['StandardScaler', 'MinMaxScaler'])

*** THESE ARE THE 93 SELECTED FEATURES (SEE VARIABLE features):
Finances
Shopping centres
Branded clothing
Entertainment spending
Spending on looks
Spending on healthy eating
Smoking
Alcohol
History
Psychology
Physics
Internet
PC
Economy Management
Biology
Geography
Foreign languages
Medicine
Law
Cars
Art exhibitions
Countryside, outdoors
Writing
Passive sport
Gardening
Science and technology
Theatre
Adrenaline sports
Pets
Movies
Thriller
Romantic
Fantasy/Fairy tales
Animated
Western
Slow songs or fast songs
Dance
Folk
Country
Musical
Pop
Rock
Metal or Hardrock
Punk
Hiphop, Rap
Swing, Jazz
Latino
Techno, Trance
Opera
Prioritising workload
Writing notes
Workaholism
Thinking ahead
Final judgement
Keeping promises
Funniness
Fake
Criminal damage
Eating to survive
Giving
Compassion to animals
Borrowed stuff
Loneliness
Cheating in school
Changing the past
God
Dreams
Charity
Number of friends
Punctuality
Lying
New environment
Mood swings
Appearence and gestures
Socializing
Achievements
Responding to a serious letter
Children
Getting angry
Knowing the right people
Public speaking
Happiness in life
Energy levels
Personality
Finding lost valuables
Getting up
Parents' advice
Internet usage
Storm
Heights
Snakes
Rats
Fear of public speaking
*************************************

*** SELECTED FEATURES BY TYPES (SEE VARIABLE features_by_type):
Finance: ['Finances', 'Shopping centres', 'Branded clothing', 'Entertainment spending', 'Spending on looks', 'Spending on healthy eating']

Health: ['Smoking', 'Alcohol']

Interests: ['History', 'Psychology', 'Physics', 'Internet', 'PC', 'Economy Management', 'Biology', 'Geography', 'Foreign languages', 'Medicine', 'Law', 'Cars', 'Art exhibitions', 'Countryside, outdoors', 'Writing', 'Passive sport', 'Gardening', 'Science and technology', 'Theatre', 'Adrenaline sports', 'Pets']

Movies: ['Movies', 'Thriller', 'Romantic', 'Fantasy/Fairy tales', 'Animated', 'Western']

Music: ['Slow songs or fast songs', 'Dance', 'Folk', 'Country', 'Musical', 'Pop', 'Rock', 'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Swing, Jazz', 'Latino', 'Techno, Trance', 'Opera']

Personality: ['Prioritising workload', 'Writing notes', 'Workaholism', 'Thinking ahead', 'Final judgement', 'Keeping promises', 'Funniness', 'Fake', 'Criminal damage', 'Eating to survive', 'Giving', 'Compassion to animals', 'Borrowed stuff', 'Loneliness', 'Cheating in school', 'Changing the past', 'God', 'Dreams', 'Charity', 'Number of friends', 'Punctuality', 'Lying', 'New environment', 'Mood swings', 'Appearence and gestures', 'Socializing', 'Achievements', 'Responding to a serious letter', 'Children', 'Getting angry', 'Knowing the right people', 'Public speaking', 'Happiness in life', 'Energy levels', 'Personality', 'Finding lost valuables', 'Getting up', "Parents' advice", 'Internet usage']

Phobias: ['Storm', 'Heights', 'Snakes', 'Rats', 'Fear of public speaking']

*************************************

*** THESE ARE THE LABELS (SEE VARIABLE labels):
Age
Height
Weight
Number of siblings
Gender
Hand
Education
Only child
Home Town Type
Home Type
*************************************

*** THIS IS YOUR PERSONAL DATASET (features AND labels TOGETHER, SEE VARIABLE responses)

,Finances,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on healthy eating,Smoking,Alcohol,History,Psychology,...,Age,Height,Weight,Number of siblings,Gender,Hand,Education,Only child,Home Town Type,Home Type
649,3,3,2,2,2,4,tried smoking,social drinker,3,4,...,19,178,88,0,female,right,secondary school,yes,city,block of flats
605,4,4,2,5,2,3,tried smoking,drink a lot,4,2,...,22,174,83,1,male,right,college/bachelor degree,no,village,house/bungalow
9,2,2,1,3,1,2,tried smoking,never,2,2,...,17,176,60,1,female,right,primary school,no,city,block of flats
194,4,4,4,4,4,5,never smoked,social drinker,4,1,...,24,177,80,0,male,right,secondary school,yes,village,house/bungalow
514,3,4,3,3,3,3,never smoked,social drinker,2,2,...,20,197,100,1,male,right,college/bachelor degree,no,village,house/bungalow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,2,1,4,4,5,4,current smoker,social drinker,5,5,...,20,169,64,0,female,right,college/bachelor degree,yes,city,house/bungalow
394,3,4,2,2,3,2,tried smoking,social drinker,1,1,...,23,172,64,1,female,right,college/bachelor degree,no,city,block of flats
243,2,4,4,2,2,4,tried smoking,social drinker,5,2,...,18,160,50,2,female,right,primary school,no,city,block of flats
432,4,3,4,3,3,4,tried smoking,social drinker,2,3,...,19,163,50,1,female,right,secondary school,yes,city,block of flats
180,3,5,1,4,3,4,tried smoking,social drinker,2,2,...,19,164,60,2,female,right,secondary school,no,village,house/bungalow

*** THIS IS YOUR PERSONAL DATASET (features, SEE VARIABLE responses_ft)

,Finances,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on healthy eating,Smoking,Alcohol,History,Psychology,...,Personality,Finding lost valuables,Getting up,Parents' advice,Internet usage,Storm,Heights,Snakes,Rats,Fear of public speaking
649,3,3,2,2,2,4,tried smoking,social drinker,3,4,...,3,4,3,4,less than an hour a day,4,3,5,1,3
605,4,4,2,5,2,3,tried smoking,drink a lot,4,2,...,3,3,4,3,few hours a day,2,2,5,3,2
9,2,2,1,3,1,2,tried smoking,never,2,2,...,3,3,5,4,few hours a day,1,3,5,5,5
194,4,4,4,4,4,5,never smoked,social drinker,4,1,...,4,2,4,3,less than an hour a day,3,1,4,2,4
514,3,4,3,3,3,3,never smoked,social drinker,2,2,...,4,1,2,3,few hours a day,2,2,5,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,2,1,4,4,5,4,current smoker,social drinker,5,5,...,4,4,2,3,few hours a day,4,5,5,1,3
394,3,4,2,2,3,2,tried smoking,social drinker,1,1,...,4,3,3,4,most of the day,5,3,5,4,3
243,2,4,4,2,2,4,tried smoking,social drinker,5,2,...,3,3,1,4,few hours a day,4,2,5,2,1
432,4,3,4,3,3,4,tried smoking,social drinker,2,3,...,3,3,4,3,few hours a day,3,3,5,5,1
180,3,5,1,4,3,4,tried smoking,social drinker,2,2,...,3,4,5,3,few hours a day,3,5,3,2,3

*** THIS IS YOUR PERSONAL DATASET (labels, SEE VARIABLE responses_lb)

,Age,Height,Weight,Number of siblings,Gender,Hand,Education,Only child,Home Town Type,Home Type
649,19,178,88,0,female,right,secondary school,yes,city,block of flats
605,22,174,83,1,male,right,college/bachelor degree,no,village,house/bungalow
9,17,176,60,1,female,right,primary school,no,city,block of flats
194,24,177,80,0,male,right,secondary school,yes,village,house/bungalow
514,20,197,100,1,male,right,college/bachelor degree,no,village,house/bungalow
...,...,...,...,...,...,...,...,...,...,...
220,20,169,64,0,female,right,college/bachelor degree,yes,city,house/bungalow
394,23,172,64,1,female,right,college/bachelor degree,no,city,block of flats
243,18,160,50,2,female,right,primary school,no,city,block of flats
432,19,163,50,1,female,right,secondary school,yes,city,block of flats
180,19,164,60,2,female,right,secondary school,no,village,house/bungalow

## Exercise 0.2: Importing Modules

In the following cell, import all the modules you think are necessary for doing the homework, **among the ones listed and used during the laboratories of the course**.

For reproducibility, **no extra modules are allowed**.

**DO NOT IMPORT NUMPY NOR PANDAS**, they are already imported.

In [8]:
# DO NOT IMPORT NUMPY AND PANDAS - Already imported
# import ...
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score

## Exercise 1. Dataset Preprocessing

In this exercise, you have to do the following operations on the dataset of the features **responses_ft**:
1. Create a new dataframe called **responses_ft_enc** by encoding the categorical features (if they exist), motivating your choices;
1. Create a new dataframe called **responses_ft_pp** by preprocessing the data in **responses_ft_enc**, according to the scaler reported in the cell below.

In [ ]:
print(f'*** YOU HAVE TO APPLY A PREPROCESSING USING THE {your_scaler}')

For doing this exercise, fill the cells below following the instructions you read.

#### Describe and motivate the encoding operations you will apply (max 150 words):
...

#### Describe the preprocessing operation you will apply and comment the effects it may have on the data (max 150 words):
...

#### Write the code for performing the encoding and preprocessing operations of the exercise. Show the encoded data and the preprocessed data you obtain, plus any additional table/value that can be useful for commenting the results:

In [ ]:
# [write the code here]

#### Comment the results obtained after the preprocessing operation (max 100 words):
...

## Exercise 2. Analyzing the Variance and the PCs

In this exercise, you have to do the following operations:
1. compute and visualize the variance of all the features in *responses_ft_enc* and *responses_ft_pp*;
1. compute all the $n$ Principal Components (PCs) for *responses_ft_enc* and *responses_ft_pp*, separately, and visualize the curves of the cumulative explained variances.

For doing this exercise, fill the cells below following the instructions you read.

#### Write the code for computing and visualizing the variance of the features of the two datasets:

In [ ]:
# [write the code here]

#### Comment the results obtained for the variances (max 150 words):
...

#### Write the code for computing all the $n$ PCs of the two datasets, separately, and for visualizing the curves of cumulative explained variances:

In [ ]:
# [write the code here]

#### Comment the results obtained for the cumulative explained variances, knowing the vaues in the datasets and the fetures' variances (max 150 words):

...

## Exercise 3. Dimensionality Reduction and PC Interpretation

In this exercise, you have to do the following operations:
1. For the dataset *responses_ft_pp*, compute a new PCA for performing a dimensionality reduction with respect to $m$ dimensions. The value of $m$ must be $$m = \min\{m', 5\}\,,$$ where $m'$ is the value required for obtaining $33\%$ of the total variance.
1. Visualize as a barplot the explained variance (as percentage) for each PC, and report the preserved explained variance (as percentage) by the $m$ PCs.
1. Visualize all the PCs as barplots and give an interpretation and a name to them, **motivating your choices**.
1. Transform the *responses_ft_pp* data into their $m$-dimensional representation via PCA. Store the transformed data in the variable *responses_ft_pca*;
1. Visualize the the score graph. If $m>3$, plot the score graph with respect to the first 3 PCs. All the **plots must show the names of the PCs (given at the previous step) on the axes** for better understanding the results.

#### Write the code for computing the new PCA, for visualizing the $m$ PCs as barplots:

In [ ]:
# [write the code here]

#### For each PC, write the name you assigned to it and a brief interpretation that motivate the choice (max 100 words per PC):

...

#### Write the code for visualizing the score graph (with PC names on the axis):

In [ ]:
# [write the code here]

## Exercise 4. $k$-Means

In this exercise, you have to do the following operations:
1. Run the $k$-Means for clustering the data of *responses_ft_pca*, **setting the input argument *random_state* equal to the variable *random_seed*** (i.e., the minimum of the Student IDs).

   In particular, **use the silohuette score for identifying the best value for $k\in\{3, \ldots, 10\}$** and show it by plotting how the score changes w.r.t. $k$.
1. Plot the score graph again, but add the centroids of the cluster and color the points according to their cluster.
1. Visualize the centroids coordinates as barplots and **give a name and an interpretation to them by exploiting the PC names**.


#### Write the code for performing the items of the list above:

In [ ]:
# [write the code here]

#### For each Centroid, write the name you assigned to it and a brief interpretation that motivate the choice by exploiting the PC names(max 100 words per centroid):

...

## Exercise 5. Cluster External Evaluations

In this exercise, you have to do the following operations:
1. Select a subset meaningful labels for performing an external evaluation of the clustering results.
1. For each selected label, visualize the distribution of the label in each cluster and in the whole dataset.
1. Visualize the score graph with dots colored with respect to the label value; then, visualize the clusters in separated score-graphs, coloring the points according to the label values.

#### List the Labels you consider meaningful for an external cluster evaluation and motivate your choice (max 50 words per label):

...


#### Write the code for the visualizations cited in item 2 above:

In [ ]:
# [write the code here]

#### For each selected label, comment the results observed in the visualizations (max 100 words per label):

...

## Exercise 6. Cluster Internal Evaluations

In this exercise, you have to do the following operations:
1. For each cluster, measure the corresponding average silhouette score
1. Visualize the silhouette of the clusters and the general one of the clustering and compare them


#### Write the code for computing the silhouette scores and for visualizing them:

In [ ]:
# [write the code here]

#### Comment the results, also considering the results observed previously (e.g., score graphs, centroids, etc. - max 150 words):

...